//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4005
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace bus2osm
{
	using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class osm
	{

		private osmNode[] nodeField;

		private osmRelation relationField;

		private decimal versionField;

		private string generatorField;

		public osm ()
		{
			this.versionField = ((decimal)(0.6m));
			this.generatorField = "bus2osm";
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("node")]
		public osmNode[] node {
			get { return this.nodeField; }
			set { this.nodeField = value; }
		}

		/// <remarks/>
		public osmRelation relation {
			get { return this.relationField; }
			set { this.relationField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal version {
			get { return this.versionField; }
			set { this.versionField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string generator {
			get { return this.generatorField; }
			set { this.generatorField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class osmNode
	{

		private sbyte idField;

		private bool visibleField;

		private decimal latField;

		private decimal lonField;

		public osmNode ()
		{
			this.visibleField = true;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte id {
			get { return this.idField; }
			set { this.idField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool visible {
			get { return this.visibleField; }
			set { this.visibleField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal lat {
			get { return this.latField; }
			set { this.latField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal lon {
			get { return this.lonField; }
			set { this.lonField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class osmRelation
	{

		private osmRelationMember[] memberField;

		private osmRelationTag[] tagField;

		private sbyte idField;

		private bool visibleField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("member")]
		public osmRelationMember[] member {
			get { return this.memberField; }
			set { this.memberField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tag")]
		public osmRelationTag[] tag {
			get { return this.tagField; }
			set { this.tagField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte id {
			get { return this.idField; }
			set { this.idField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool visible {
			get { return this.visibleField; }
			set { this.visibleField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class osmRelationMember
	{

		private string typeField;

		private sbyte refField;

		private osmRelationMemberRole roleField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type {
			get { return this.typeField; }
			set { this.typeField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte @ref {
			get { return this.refField; }
			set { this.refField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public osmRelationMemberRole role {
			get { return this.roleField; }
			set { this.roleField = value; }
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum osmRelationMemberRole
	{

		/// <remarks/>
		stop,

		/// <remarks/>
		forward,

		/// <remarks/>
		backward
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class osmRelationTag
	{

		private string kField;

		private string vField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string k {
			get { return this.kField; }
			set { this.kField = value; }
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string v {
			get { return this.vField; }
			set { this.vField = value; }
		}
	}
}
